// Your existing data, exported from the Claude artifact on 2026-07-07. Seeded
// into the browser's localStorage the first time the app runs on a device.
const seed = {
  entries: [
    {
      id: 'entry_1783134622115_cvb8t',
      keepsakeName: 'Crystal Figurine',
      emoji: '🐷',
      datetime: '2026-07-03T14:00',
      title: 'Galbi-jjim for Days',
      content:
        "Lunch at Moo Bong Ri with @Gary and @Dalena was delicious, and adding glass noodles to the Galbi-jjim was a solid choice. There is *so* much left over that I'm going to try and stretch across three meals. @Dalena threw up from overeating at the restaurant though, and I felt really bad about it.",
      createdAt: '2026-07-04T03:10:22.115Z',
      updatedAt: '2026-07-04T03:26:04.270Z',
    },
    {
      id: 'entry_1783367361522_zamv8',
      keepsakeName: 'Blood-filled Vial',
      emoji: '🩸',
      datetime: '2026-07-06T12:43',
      title: 'Car Maintenance',
      content:
        'I officially despise owning a car. How were there already 4-5 other people at the dealership at 6:30 in the morning? And how did a basic maintenance trip turn into me draining my bank account? Absolute garbage way to start a morning.',
      createdAt: '2026-07-06T19:49:21.522Z',
    },
  ],
  moods: {
    1: ['meh', 'sick'],
    2: ['ok', 'tired'],
    3: ['meh'],
    4: ['tired', 'stressed'],
    5: ['meh'],
    6: ['ok'],
    7: ['ok', 'tired'],
    8: ['tired', 'stressed'],
    9: ['sick', 'tired'],
    10: ['apathetic'],
    11: ['apathetic'],
    12: ['apathetic'],
    13: ['tired'],
    14: ['tired'],
    15: ['tired'],
    16: ['tired', 'sad'],
    17: ['meh'],
    18: ['apathetic'],
    19: ['ok'],
    20: ['sad', 'tired'],
    21: ['meh', 'tired'],
    22: ['tired'],
    23: ['tired'],
    24: ['apathetic', 'sad'],
    25: ['apathetic'],
    26: ['meh', 'angry'],
    27: ['sick', 'tired'],
    28: ['angry', 'tired'],
    29: ['angry'],
    30: ['tired'],
    31: ['meh'],
    32: ['tired'],
    33: ['apathetic'],
    34: ['ok'],
    35: ['stressed', 'tired'],
    36: ['meh'],
    37: ['tired'],
    38: ['apathetic'],
    39: ['meh'],
    40: ['tired'],
    41: ['stressed'],
    42: ['meh'],
    91: ['meh'],
    92: ['tired'],
    93: ['tired', 'sad'],
    94: ['tired'],
    95: ['apathetic'],
    96: ['tired'],
    152: ['ok', 'meh'],
    153: ['meh', 'apathetic'],
    154: ['tired'],
    155: ['tired', 'stressed'],
    156: ['tired', 'meh'],
    157: ['ok', 'happy'],
    158: ['meh', 'apathetic'],
    164: ['tired', 'meh'],
    165: ['ok'],
    166: ['angry', 'apathetic'],
    182: ['ok', 'tired'],
    183: ['tired'],
    184: ['ok', 'meh'],
    185: ['meh', 'apathetic'],
    186: ['meh'],
    187: ['apathetic'],
    188: ['tired', 'apathetic'],
  },
};

export default seed;
